import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class makeHashMap {
    public static Map<String, List<String>> makemoveList() {
        HashMap<String, List<String>> result = new HashMap<>();
        result.put("A1 c1", new ArrayList<String>(Arrays.asList("")));
        result.put("A2 c1", new ArrayList<String>(Arrays.asList("A1")));
        result.put("A3 c1", new ArrayList<String>(Arrays.asList("A2")));
        result.put("A4 c1", new ArrayList<String>(Arrays.asList("A3")));
        result.put("B1 c1", new ArrayList<String>(Arrays.asList("")));
        result.put("B2 c1", new ArrayList<String>(Arrays.asList("B1")));
        result.put("B3 c1", new ArrayList<String>(Arrays.asList("B2")));
        result.put("B4 c1", new ArrayList<String>(Arrays.asList("B3")));
        result.put("C1 c1", new ArrayList<String>(Arrays.asList("")));
        result.put("C2 c1", new ArrayList<String>(Arrays.asList("C1")));
        result.put("C3 c1", new ArrayList<String>(Arrays.asList("C2")));
        result.put("C4 c1", new ArrayList<String>(Arrays.asList("C3")));
        result.put("A1 c2", new ArrayList<String>(Arrays.asList("A2")));
        result.put("A2 c2", new ArrayList<String>(Arrays.asList("A3")));
        result.put("A3 c2", new ArrayList<String>(Arrays.asList("A4")));
        result.put("A4 c2", new ArrayList<String>(Arrays.asList("")));
        result.put("B1 c2", new ArrayList<String>(Arrays.asList("B2")));
        result.put("B2 c2", new ArrayList<String>(Arrays.asList("B3")));
        result.put("B3 c2", new ArrayList<String>(Arrays.asList("B4")));
        result.put("B4 c2", new ArrayList<String>(Arrays.asList("")));
        result.put("C1 c2", new ArrayList<String>(Arrays.asList("C2")));
        result.put("C2 c2", new ArrayList<String>(Arrays.asList("C3")));
        result.put("C3 c2", new ArrayList<String>(Arrays.asList("C4")));
        result.put("C4 c2", new ArrayList<String>(Arrays.asList("")));
        result.put("A1 g1", new ArrayList<String>(Arrays.asList("A2", "B1")));
        result.put("A2 g1", new ArrayList<String>(Arrays.asList("A3", "B2", "A1")));
        result.put("A3 g1", new ArrayList<String>(Arrays.asList("A4", "B3", "A2")));
        result.put("A4 g1", new ArrayList<String>(Arrays.asList("B4", "A3")));
        result.put("B1 g1", new ArrayList<String>(Arrays.asList("B2", "C1", "A1")));
        result.put("B2 g1", new ArrayList<String>(Arrays.asList("B3", "C2", "A2", "B1")));
        result.put("B3 g1", new ArrayList<String>(Arrays.asList("B4", "C3", "A3", "B2")));
        result.put("B4 g1", new ArrayList<String>(Arrays.asList("C4", "A4", "B3")));
        result.put("C1 g1", new ArrayList<String>(Arrays.asList("C2", "B1")));
        result.put("C2 g1", new ArrayList<String>(Arrays.asList("C3", "B2", "C1")));
        result.put("C3 g1", new ArrayList<String>(Arrays.asList("C4", "B3", "C2")));
        result.put("C4 g1", new ArrayList<String>(Arrays.asList("B4", "C3")));
        result.put("A1 g2", new ArrayList<String>(Arrays.asList("A2", "B1")));
        result.put("A2 g2", new ArrayList<String>(Arrays.asList("A3", "B2", "A1")));
        result.put("A3 g2", new ArrayList<String>(Arrays.asList("A4", "B3", "A2")));
        result.put("A4 g2", new ArrayList<String>(Arrays.asList("B4", "A3")));
        result.put("B1 g2", new ArrayList<String>(Arrays.asList("B2", "C1", "A1")));
        result.put("B2 g2", new ArrayList<String>(Arrays.asList("B3", "C2", "A2", "B1")));
        result.put("B3 g2", new ArrayList<String>(Arrays.asList("B4", "C3", "A3", "B2")));
        result.put("B4 g2", new ArrayList<String>(Arrays.asList("C4", "A4", "B3")));
        result.put("C1 g2", new ArrayList<String>(Arrays.asList("C2", "B1")));
        result.put("C2 g2", new ArrayList<String>(Arrays.asList("C3", "B2", "C1")));
        result.put("C3 g2", new ArrayList<String>(Arrays.asList("C4", "B3", "C2")));
        result.put("C4 g2", new ArrayList<String>(Arrays.asList("B4", "C3")));
        result.put("A1 e1", new ArrayList<String>(Arrays.asList("B2")));
        result.put("A2 e1", new ArrayList<String>(Arrays.asList("B3", "B1")));
        result.put("A3 e1", new ArrayList<String>(Arrays.asList("B4", "B2")));
        result.put("A4 e1", new ArrayList<String>(Arrays.asList("B3")));
        result.put("B1 e1", new ArrayList<String>(Arrays.asList("C2", "A2")));
        result.put("B2 e1", new ArrayList<String>(Arrays.asList("C3", "A3", "A1", "C1")));
        result.put("B3 e1", new ArrayList<String>(Arrays.asList("C4", "A4", "A2", "C2")));
        result.put("B4 e1", new ArrayList<String>(Arrays.asList("A3", "C3")));
        result.put("C1 e1", new ArrayList<String>(Arrays.asList("B2")));
        result.put("C2 e1", new ArrayList<String>(Arrays.asList("B3", "B1")));
        result.put("C3 e1", new ArrayList<String>(Arrays.asList("B4", "B2")));
        result.put("C4 e1", new ArrayList<String>(Arrays.asList("B3")));
        result.put("A1 e2", new ArrayList<String>(Arrays.asList("B2")));
        result.put("A2 e2", new ArrayList<String>(Arrays.asList("B3", "B1")));
        result.put("A3 e2", new ArrayList<String>(Arrays.asList("B4", "B2")));
        result.put("A4 e2", new ArrayList<String>(Arrays.asList("B3")));
        result.put("B1 e2", new ArrayList<String>(Arrays.asList("C2", "A2")));
        result.put("B2 e2", new ArrayList<String>(Arrays.asList("C3", "A3", "A1", "C1")));
        result.put("B3 e2", new ArrayList<String>(Arrays.asList("C4", "A4", "A2", "C2")));
        result.put("B4 e2", new ArrayList<String>(Arrays.asList("A3", "C3")));
        result.put("C1 e2", new ArrayList<String>(Arrays.asList("B2")));
        result.put("C2 e2", new ArrayList<String>(Arrays.asList("B3", "B1")));
        result.put("C3 e2", new ArrayList<String>(Arrays.asList("B4", "B2")));
        result.put("C4 e2", new ArrayList<String>(Arrays.asList("B3")));
        result.put("A1 h1", new ArrayList<String>(Arrays.asList("A2", "B1")));
        result.put("A2 h1", new ArrayList<String>(Arrays.asList("A3", "B1", "B2", "A1")));
        result.put("A3 h1", new ArrayList<String>(Arrays.asList("A4", "B2", "B3", "A2")));
        result.put("A4 h1", new ArrayList<String>(Arrays.asList("B3", "B4", "A3")));
        result.put("B1 h1", new ArrayList<String>(Arrays.asList("B2", "C1", "A1")));
        result.put("B2 h1", new ArrayList<String>(Arrays.asList("B3", "C1", "C2", "A1", "A2", "B1")));
        result.put("B3 h1", new ArrayList<String>(Arrays.asList("B4", "C2", "C3", "A2", "A3", "B2")));
        result.put("B4 h1", new ArrayList<String>(Arrays.asList("C3", "C4", "A3", "A4", "B3")));
        result.put("C1 h1", new ArrayList<String>(Arrays.asList("C2", "B1")));
        result.put("C2 h1", new ArrayList<String>(Arrays.asList("C3", "B1", "B2", "C1")));
        result.put("C3 h1", new ArrayList<String>(Arrays.asList("C4", "B2", "B3", "C2")));
        result.put("C4 h1", new ArrayList<String>(Arrays.asList("B3", "B4", "C3")));
        result.put("A1 h2", new ArrayList<String>(Arrays.asList("B1", "B2", "A2")));
        result.put("A2 h2", new ArrayList<String>(Arrays.asList("B2", "B3", "A1", "A3")));
        result.put("A3 h2", new ArrayList<String>(Arrays.asList("B3", "B4", "A2", "A4")));
        result.put("A4 h2", new ArrayList<String>(Arrays.asList("B4", "A3")));
        result.put("B1 h2", new ArrayList<String>(Arrays.asList("C1", "C2", "A2", "A1", "B2")));
        result.put("B2 h2", new ArrayList<String>(Arrays.asList("C2", "C3", "A3", "A2", "B1", "B3")));
        result.put("B3 h2", new ArrayList<String>(Arrays.asList("C3", "C4", "A4", "A3", "B2", "B4")));
        result.put("B4 h2", new ArrayList<String>(Arrays.asList("C4", "A4", "B3")));
        result.put("C1 h2", new ArrayList<String>(Arrays.asList("B2", "B1", "C2")));
        result.put("C2 h2", new ArrayList<String>(Arrays.asList("B3", "B2", "C1", "C3")));
        result.put("C3 h2", new ArrayList<String>(Arrays.asList("B4", "B3", "C2", "C4")));
        result.put("C4 h2", new ArrayList<String>(Arrays.asList("B4", "C3")));
        result.put("A1 l1", new ArrayList<String>(Arrays.asList("B1", "B2", "A2")));
        result.put("A2 l1", new ArrayList<String>(Arrays.asList("A1", "B1", "B2", "B3", "A3")));
        result.put("A3 l1", new ArrayList<String>(Arrays.asList("A2", "B2", "B3", "B4", "A4")));
        result.put("A4 l1", new ArrayList<String>(Arrays.asList("A3", "B3", "B4")));
        result.put("B1 l1", new ArrayList<String>(Arrays.asList("C1", "A1", "C2", "A2", "B2")));
        result.put("B2 l1", new ArrayList<String>(Arrays.asList("B1", "C1", "A1", "C2", "A2", "C3", "A3", "B3")));
        result.put("B3 l1", new ArrayList<String>(Arrays.asList("B2", "C2", "A2", "C3", "A3", "C4", "A4", "B4")));
        result.put("B4 l1", new ArrayList<String>(Arrays.asList("B3", "C3", "A3", "C4", "A4")));
        result.put("C1 l1", new ArrayList<String>(Arrays.asList("B1", "B2", "C2")));
        result.put("C2 l1", new ArrayList<String>(Arrays.asList("C1", "B1", "B2", "B3", "C3")));
        result.put("C3 l1", new ArrayList<String>(Arrays.asList("C2", "B2", "B3", "B4", "C4")));
        result.put("C4 l1", new ArrayList<String>(Arrays.asList("C3", "B3", "B4")));
        result.put("A1 l2", new ArrayList<String>(Arrays.asList("B1", "B2", "A2")));
        result.put("A2 l2", new ArrayList<String>(Arrays.asList("A1", "B1", "B2", "B3", "A3")));
        result.put("A3 l2", new ArrayList<String>(Arrays.asList("A2", "B2", "B3", "B4", "A4")));
        result.put("A4 l2", new ArrayList<String>(Arrays.asList("A3", "B3", "B4")));
        result.put("B1 l2", new ArrayList<String>(Arrays.asList("C1", "A1", "C2", "A2", "B2")));
        result.put("B2 l2", new ArrayList<String>(Arrays.asList("B1", "C1", "A1", "C2", "A2", "C3", "A3", "B3")));
        result.put("B3 l2", new ArrayList<String>(Arrays.asList("B2", "C2", "A2", "C3", "A3", "C4", "A4", "B4")));
        result.put("B4 l2", new ArrayList<String>(Arrays.asList("B3", "C3", "A3", "C4", "A4")));
        result.put("C1 l2", new ArrayList<String>(Arrays.asList("B1", "B2", "C2")));
        result.put("C2 l2", new ArrayList<String>(Arrays.asList("C1", "B1", "B2", "B3", "C3")));
        result.put("C3 l2", new ArrayList<String>(Arrays.asList("C2", "B2", "B3", "B4", "C4")));
        result.put("C4 l2", new ArrayList<String>(Arrays.asList("C3", "B3", "B4")));

        return Collections.unmodifiableMap(result);
    }

    public static Map<String, Integer> evaluationList1() {
        HashMap<String, Integer> evaList = new HashMap<>();
        evaList.put("A1 c1", 1);
        evaList.put("A2 c1", 1);
        evaList.put("A3 c1", 1);
        evaList.put("A4 c1", 1);
        evaList.put("B1 c1", 1);
        evaList.put("B2 c1", 1);
        evaList.put("B3 c1", 1);
        evaList.put("B4 c1", 1);
        evaList.put("C1 c1", 1);
        evaList.put("C2 c1", 1);
        evaList.put("C3 c1", 1);
        evaList.put("C4 c1", 1);
        evaList.put("A1 c2", -1);
        evaList.put("A2 c2", -1);
        evaList.put("A3 c2", -1);
        evaList.put("A4 c2", -1);
        evaList.put("B1 c2", -1);
        evaList.put("B2 c2", -1);
        evaList.put("B3 c2", -1);
        evaList.put("B4 c2", -1);
        evaList.put("C1 c2", -1);
        evaList.put("C2 c2", -1);
        evaList.put("C3 c2", -1);
        evaList.put("C4 c2", -1);
        evaList.put("A1 g1", 5);
        evaList.put("A2 g1", 5);
        evaList.put("A3 g1", 5);
        evaList.put("A4 g1", 5);
        evaList.put("B1 g1", 5);
        evaList.put("B2 g1", 5);
        evaList.put("B3 g1", 5);
        evaList.put("B4 g1", 5);
        evaList.put("C1 g1", 5);
        evaList.put("C2 g1", 5);
        evaList.put("C3 g1", 5);
        evaList.put("C4 g1", 5);
        evaList.put("A1 g2", -5);
        evaList.put("A2 g2", -5);
        evaList.put("A3 g2", -5);
        evaList.put("A4 g2", -5);
        evaList.put("B1 g2", -5);
        evaList.put("B2 g2", -5);
        evaList.put("B3 g2", -5);
        evaList.put("B4 g2", -5);
        evaList.put("C1 g2", -5);
        evaList.put("C2 g2", -5);
        evaList.put("C3 g2", -5);
        evaList.put("C4 g2", -5);
        evaList.put("A1 e1", 6);
        evaList.put("A2 e1", 6);
        evaList.put("A3 e1", 6);
        evaList.put("A4 e1", 6);
        evaList.put("B1 e1", 6);
        evaList.put("B2 e1", 6);
        evaList.put("B3 e1", 6);
        evaList.put("B4 e1", 6);
        evaList.put("C1 e1", 6);
        evaList.put("C2 e1", 6);
        evaList.put("C3 e1", 6);
        evaList.put("C4 e1", 6);
        evaList.put("A1 e2", -6);
        evaList.put("A2 e2", -6);
        evaList.put("A3 e2", -6);
        evaList.put("A4 e2", -6);
        evaList.put("B1 e2", -6);
        evaList.put("B2 e2", -6);
        evaList.put("B3 e2", -6);
        evaList.put("B4 e2", -6);
        evaList.put("C1 e2", -6);
        evaList.put("C2 e2", -6);
        evaList.put("C3 e2", -6);
        evaList.put("C4 e2", -6);
        evaList.put("A1 h1", 6);
        evaList.put("A2 h1", 6);
        evaList.put("A3 h1", 6);
        evaList.put("A4 h1", 6);
        evaList.put("B1 h1", 6);
        evaList.put("B2 h1", 6);
        evaList.put("B3 h1", 6);
        evaList.put("B4 h1", 6);
        evaList.put("C1 h1", 6);
        evaList.put("C2 h1", 6);
        evaList.put("C3 h1", 6);
        evaList.put("C4 h1", 6);
        evaList.put("A1 h2", -6);
        evaList.put("A2 h2", -6);
        evaList.put("A3 h2", -6);
        evaList.put("A4 h2", -6);
        evaList.put("B1 h2", -6);
        evaList.put("B2 h2", -6);
        evaList.put("B3 h2", -6);
        evaList.put("B4 h2", -6);
        evaList.put("C1 h2", -6);
        evaList.put("C2 h2", -6);
        evaList.put("C3 h2", -6);
        evaList.put("C4 h2", -6);
        evaList.put("A1 l1", 0);
        evaList.put("A2 l1", 0);
        evaList.put("A3 l1", 0);
        evaList.put("A4 l1", 0);
        evaList.put("B1 l1", 0);
        evaList.put("B2 l1", 0);
        evaList.put("B3 l1", 0);
        evaList.put("B4 l1", 0);
        evaList.put("C1 l1", 0);
        evaList.put("C2 l1", 0);
        evaList.put("C3 l1", 0);
        evaList.put("C4 l1", 0);
        evaList.put("A1 l2", 0);
        evaList.put("A2 l2", 0);
        evaList.put("A3 l2", 0);
        evaList.put("A4 l2", 0);
        evaList.put("B1 l2", 0);
        evaList.put("B2 l2", 0);
        evaList.put("B3 l2", 0);
        evaList.put("B4 l2", 0);
        evaList.put("C1 l2", 0);
        evaList.put("C2 l2", 0);
        evaList.put("C3 l2", 0);
        evaList.put("C4 l2", 0);
        evaList.put("D1 c1", 3);
        evaList.put("D2 c1", 3);
        evaList.put("D3 c1", 3);
        evaList.put("D4 c1", 3);
        evaList.put("D5 c1", 3);
        evaList.put("D6 c1", 3);
        evaList.put("E1 c2", -3);
        evaList.put("E2 c2", -3);
        evaList.put("E3 c2", -3);
        evaList.put("E4 c2", -3);
        evaList.put("E5 c2", -3);
        evaList.put("E6 c2", -3);
        evaList.put("D1 g1", 7);
        evaList.put("D2 g1", 7);
        evaList.put("D3 g1", 7);
        evaList.put("D4 g1", 7);
        evaList.put("D5 g1", 7);
        evaList.put("D6 g1", 7);
        evaList.put("E1 g2", -7);
        evaList.put("E2 g2", -7);
        evaList.put("E3 g2", -7);
        evaList.put("E4 g2", -7);
        evaList.put("E5 g2", -7);
        evaList.put("E6 g2", -7);
        evaList.put("D1 e1", 8);
        evaList.put("D2 e1", 8);
        evaList.put("D3 e1", 8);
        evaList.put("D4 e1", 8);
        evaList.put("D5 e1", 8);
        evaList.put("D6 e1", 8);
        evaList.put("E1 e2", -8);
        evaList.put("E2 e2", -8);
        evaList.put("E3 e2", -8);
        evaList.put("E4 e2", -8);
        evaList.put("E5 e2", -8);
        evaList.put("E6 e2", -8);
        evaList.put("D1 l1", 0);
        evaList.put("D2 l1", 0);
        evaList.put("D3 l1", 0);
        evaList.put("D4 l1", 0);
        evaList.put("D5 l1", 0);
        evaList.put("D6 l1", 0);
        evaList.put("E1 l2", 0);
        evaList.put("E2 l2", 0);
        evaList.put("E3 l2", 0);
        evaList.put("E4 l2", 0);
        evaList.put("E5 l2", 0);
        evaList.put("E6 l2", 0);
        return Collections.unmodifiableMap(evaList);
    }

    public static Map<String, Integer> evaluationList2() {
        HashMap<String, Integer> evaList = new HashMap<>();
        evaList.put("A1 c1", -1);
        evaList.put("A2 c1", -1);
        evaList.put("A3 c1", -1);
        evaList.put("A4 c1", -1);
        evaList.put("B1 c1", -1);
        evaList.put("B2 c1", -1);
        evaList.put("B3 c1", -1);
        evaList.put("B4 c1", -1);
        evaList.put("C1 c1", -1);
        evaList.put("C2 c1", -1);
        evaList.put("C3 c1", -1);
        evaList.put("C4 c1", -1);
        evaList.put("A1 c2", 1);
        evaList.put("A2 c2", 1);
        evaList.put("A3 c2", 1);
        evaList.put("A4 c2", 1);
        evaList.put("B1 c2", 1);
        evaList.put("B2 c2", 1);
        evaList.put("B3 c2", 1);
        evaList.put("B4 c2", 1);
        evaList.put("C1 c2", 1);
        evaList.put("C2 c2", 1);
        evaList.put("C3 c2", 1);
        evaList.put("C4 c2", 1);
        evaList.put("A1 g1", -5);
        evaList.put("A2 g1", -5);
        evaList.put("A3 g1", -5);
        evaList.put("A4 g1", -5);
        evaList.put("B1 g1", -5);
        evaList.put("B2 g1", -5);
        evaList.put("B3 g1", -5);
        evaList.put("B4 g1", -5);
        evaList.put("C1 g1", -5);
        evaList.put("C2 g1", -5);
        evaList.put("C3 g1", -5);
        evaList.put("C4 g1", -5);
        evaList.put("A1 g2", 5);
        evaList.put("A2 g2", 5);
        evaList.put("A3 g2", 5);
        evaList.put("A4 g2", 5);
        evaList.put("B1 g2", 5);
        evaList.put("B2 g2", 5);
        evaList.put("B3 g2", 5);
        evaList.put("B4 g2", 5);
        evaList.put("C1 g2", 5);
        evaList.put("C2 g2", 5);
        evaList.put("C3 g2", 5);
        evaList.put("C4 g2", 5);
        evaList.put("A1 e1", -6);
        evaList.put("A2 e1", -6);
        evaList.put("A3 e1", -6);
        evaList.put("A4 e1", -6);
        evaList.put("B1 e1", -6);
        evaList.put("B2 e1", -6);
        evaList.put("B3 e1", -6);
        evaList.put("B4 e1", -6);
        evaList.put("C1 e1", -6);
        evaList.put("C2 e1", -6);
        evaList.put("C3 e1", -6);
        evaList.put("C4 e1", -6);
        evaList.put("A1 e2", 6);
        evaList.put("A2 e2", 6);
        evaList.put("A3 e2", 6);
        evaList.put("A4 e2", 6);
        evaList.put("B1 e2", 6);
        evaList.put("B2 e2", 6);
        evaList.put("B3 e2", 6);
        evaList.put("B4 e2", 6);
        evaList.put("C1 e2", 6);
        evaList.put("C2 e2", 6);
        evaList.put("C3 e2", 6);
        evaList.put("C4 e2", 6);
        evaList.put("A1 h1", -6);
        evaList.put("A2 h1", -6);
        evaList.put("A3 h1", -6);
        evaList.put("A4 h1", -6);
        evaList.put("B1 h1", -6);
        evaList.put("B2 h1", -6);
        evaList.put("B3 h1", -6);
        evaList.put("B4 h1", -6);
        evaList.put("C1 h1", -6);
        evaList.put("C2 h1", -6);
        evaList.put("C3 h1", -6);
        evaList.put("C4 h1", -6);
        evaList.put("A1 h2", 6);
        evaList.put("A2 h2", 6);
        evaList.put("A3 h2", 6);
        evaList.put("A4 h2", 6);
        evaList.put("B1 h2", 6);
        evaList.put("B2 h2", 6);
        evaList.put("B3 h2", 6);
        evaList.put("B4 h2", 6);
        evaList.put("C1 h2", 6);
        evaList.put("C2 h2", 6);
        evaList.put("C3 h2", 6);
        evaList.put("C4 h2", 6);
        evaList.put("A1 l1", 0);
        evaList.put("A2 l1", 0);
        evaList.put("A3 l1", 0);
        evaList.put("A4 l1", 0);
        evaList.put("B1 l1", 0);
        evaList.put("B2 l1", 0);
        evaList.put("B3 l1", 0);
        evaList.put("B4 l1", 0);
        evaList.put("C1 l1", 0);
        evaList.put("C2 l1", 0);
        evaList.put("C3 l1", 0);
        evaList.put("C4 l1", 0);
        evaList.put("A1 l2", 0);
        evaList.put("A2 l2", 0);
        evaList.put("A3 l2", 0);
        evaList.put("A4 l2", 0);
        evaList.put("B1 l2", 0);
        evaList.put("B2 l2", 0);
        evaList.put("B3 l2", 0);
        evaList.put("B4 l2", 0);
        evaList.put("C1 l2", 0);
        evaList.put("C2 l2", 0);
        evaList.put("C3 l2", 0);
        evaList.put("C4 l2", 0);
        evaList.put("D1 c1", -3);
        evaList.put("D2 c1", -3);
        evaList.put("D3 c1", -3);
        evaList.put("D4 c1", -3);
        evaList.put("D5 c1", -3);
        evaList.put("D6 c1", -3);
        evaList.put("E1 c2", 3);
        evaList.put("E2 c2", 3);
        evaList.put("E3 c2", 3);
        evaList.put("E4 c2", 3);
        evaList.put("E5 c2", 3);
        evaList.put("E6 c2", 3);
        evaList.put("D1 g1", -7);
        evaList.put("D2 g1", -7);
        evaList.put("D3 g1", -7);
        evaList.put("D4 g1", -7);
        evaList.put("D5 g1", -7);
        evaList.put("D6 g1", -7);
        evaList.put("E1 g2", 7);
        evaList.put("E2 g2", 7);
        evaList.put("E3 g2", 7);
        evaList.put("E4 g2", 7);
        evaList.put("E5 g2", 7);
        evaList.put("E6 g2", 7);
        evaList.put("D1 e1", -8);
        evaList.put("D2 e1", -8);
        evaList.put("D3 e1", -8);
        evaList.put("D4 e1", -8);
        evaList.put("D5 e1", -8);
        evaList.put("D6 e1", -8);
        evaList.put("E1 e2", 8);
        evaList.put("E2 e2", 8);
        evaList.put("E3 e2", 8);
        evaList.put("E4 e2", 8);
        evaList.put("E5 e2", 8);
        evaList.put("E6 e2", 8);
        evaList.put("D1 l1", 0);
        evaList.put("D2 l1", 0);
        evaList.put("D3 l1", 0);
        evaList.put("D4 l1", 0);
        evaList.put("D5 l1", 0);
        evaList.put("D6 l1", 0);
        evaList.put("E1 l2", 0);
        evaList.put("E2 l2", 0);
        evaList.put("E3 l2", 0);
        evaList.put("E4 l2", 0);
        evaList.put("E5 l2", 0);
        evaList.put("E6 l2", 0);
        return Collections.unmodifiableMap(evaList);
    }
}
